name: agro-predict

services:
  mariadb:
    image: mariadb:10.11
    container_name: agro-predict-db
    environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
        - "3307:3306"
    volumes:
        - mariadb_data:/var/lib/mysql 
    restart: unless-stopped
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 20s  

  cache:
    image: redis:7.4-alpine
    container_name: agro-predict-cache
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASS} # Almacena datos cada 20 seg, solo muestra warnings
    volumes:
      - cache:/data

  mcp-server:
    image: mendo1/agro-predict:mcp-server-1.0
    container_name: mcp-server
    volumes:
      - mcp_data:/var/lib/server
    ports:
      - "9001:9001"
    restart: unless-stopped
  
  ollama:
    image: mendo1/agro-predict:model-ollama-1.0
    container_name: ollama-service
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=${PARALLEL} # Número de solicitudes paralelas
      - OLLAMA_MAX_LOADED_MODELS=${MODELS} # Número máximo de modelos a cargar en Ollama
      - OLLAMA_KEEP_ALIVE=${KEEP_ALIVE} # Tiempo que perdurarán los modelos en memoria
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    deploy:
      resources:
        limits:
          cpus: '6.0'
          memory: 10G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  aemet-service:
    image: mendo1/agro-predict:aemet-service-1.0
    container_name: aemet-service
    environment:
      - AEMET_API_KEY=${AEMET_API_KEY}
      - AEMET_BASE_URL=${AEMET_BASE_URL}
      - PORT=4000
    env_file: .env
    volumes:
      - aemet-data:/app/private/aemet
    ports: 
      - "4000:4000"
    restart: unless-stopped

  siar-service:
    image: mendo1/agro-predict:siar-service-1.0
    container_name: siar-service
    environment:
      - SIAR_API_KEY=${SIAR_API_KEY}
    env_file: .env
    ports:
      - "8086:8086"
    restart: unless-stopped

volumes:
  mariadb_data:
  aemet-data:
    driver: local
  cache:
    driver: local
  mcp_data:
    driver: local
  ollama_models: