# Fase 1. Build
FROM python:3.13-slim AS build

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

# Ejecutar la instalacion de las dependencias sin tener en cuenta el pywin32, no es compatible
RUN grep -v "pywin32" requirements.txt > requirements-linux.txt && \
    pip install --no-cache-dir -r requirements-linux.txt

# Fase 2. Código de la aplicacion
FROM python:3.13-slim 

WORKDIR /app

# Copio las dependencias instaladas de la fase build
COPY --from=build /usr/local/lib/python3.13/site-packages /usr/local/lib/python3.13/site-packages
COPY --from=build /usr/local/bin /usr/local/bin

# Copiar el código de la aplicación
COPY . .

# Puerto en el que se va a exponer el contenedor
EXPOSE 9001

# Comando para ejecutar la aplicación
CMD ["python", "server.py"]