"""added new fields in mediciones_climaticas for a correct behavior in predictors

Revision ID: f0e51c8aef9b
Revises: b521ed94a494
Create Date: 2026-06-02 08:55:10.870406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0e51c8aef9b'
down_revision = 'b521ed94a494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_climaticas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('humedad_media', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humedad_maxima', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('humedad_minima', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperatura_media', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperatura_maxima', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('temperatura_minima', sa.Float(), nullable=True))
        batch_op.drop_column('temperatura')
        batch_op.drop_column('humedad')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mediciones_climaticas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('humedad', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('temperatura', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('temperatura_minima')
        batch_op.drop_column('temperatura_maxima')
        batch_op.drop_column('temperatura_media')
        batch_op.drop_column('humedad_minima')
        batch_op.drop_column('humedad_maxima')
        batch_op.drop_column('humedad_media')

    # ### end Alembic commands ###
