import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { predictor } from '$lib/server/predictor';
import { errorOutcome, pdfResponse } from '$lib/server/helpers';

const KINDS = ['heladas-observadas', 'heladas-futuras', 'plagas-calculadas', 'plagas-estimadas'];

function frostBody(payload: Record<string, unknown>): Record<string, unknown> {
const code = String(payload['code'] ?? '').trim();
const body: Record<string, unknown> = {
evaluacion: Boolean(payload['evaluacion'] ?? payload['evaluacion_var']),
variedades: Array.isArray(payload['variedades']) ? payload['variedades'] : undefined
};
if (payload['source'] === 'estacion' || payload['evaluacion_loc'] !== undefined) {
body['codigo_estacion'] = code;
} else {
body['codigo_provincia'] = code;
}
return body;
}

/**
 * Streams the digitally signed PDF reports generated by the predictors.
 * GET keeps this out of the form-action pipeline so the binary Response can be
 * returned directly to the browser.
 */
export const GET: RequestHandler = async ({ url }) => {
const kind = url.searchParams.get('kind') ?? '';
const filename = url.searchParams.get('filename') ?? 'agro-predict-report.pdf';
const payloadRaw = url.searchParams.get('payload') ?? '{}';

if (!KINDS.includes(kind)) {
return json({ message: 'Unknown report kind' }, { status: 400 });
}

let payload: Record<string, unknown>;
try {
const parsed: unknown = JSON.parse(payloadRaw);
payload = parsed && typeof parsed === 'object' ? (parsed as Record<string, unknown>) : {};
} catch {
return json({ message: 'Invalid report payload' }, { status: 400 });
}

try {
let out;
if (kind === 'heladas-observadas') {
out = await predictor.heladasObservadasPdf(
String(payload['tipo'] ?? 'Dia'),
frostBody(payload),
filename
);
} else if (kind === 'heladas-futuras') {
const zona = String(payload['zona'] ?? 'provincial');
out = await predictor.heladasFuturasPdf(zona, payload, filename);
} else if (kind === 'plagas-calculadas') {
out = await predictor.plagasCalculadasPdf(
String(payload['cultivo'] ?? ''),
filename
);
} else {
out = await predictor.plagasEstimadasPdf(payload, filename);
}

if (out.kind === 'json') {
return json({ message: 'PDF report is not available right now' }, { status: 406 });
}
return pdfResponse(out.bytes, out.filename);
} catch (err) {
const outcome = errorOutcome(err);
return json({ message: outcome.message }, { status: outcome.status });
}
};
