name: agro-predict-broker

services:
  rabbitmq:
    image: rabbitmq:latest
    container_name : rabbitmq_broker
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    networks:
      - broker
    volumes:
      - rabbitmq-lib:/var/lib/rabbitmq
      - rabbitmq-log:/var/log/rabbitmq
      - ./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins # Habilitar plugins adicionales

networks:
  broker:
    external: true

volumes:
  rabbitmq-lib:
    driver: local
  rabbitmq-log:
    driver: local