# Dockerfile para ollama
FROM ollama/ollama:latest

# Expongo el puerto por defecto de Ollama
EXPOSE 11434

# Creo un volumen de modelos para evitar descargarlos constantemente
VOLUME ["/root/.ollama"]

# Script de inicio que precarga el modelo
COPY ./scripts/preload-model.sh /preload-model.sh
RUN sed -i 's/\r$//' /preload-model.sh && chmod +x /preload-model.sh

# Ejecución de ollama
ENTRYPOINT []
CMD ["/bin/sh", "/preload-model.sh"]